/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BoasVindasRouteImport } from './routes/boas-vindas'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as RecomendacoesRouteImport } from './routes/recomendacoes'
import { Route as SocialNetworkRouteImport } from './routes/social.$network'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BoasVindasRoute = BoasVindasRouteImport.update({
  id: '/boas-vindas',
  path: '/boas-vindas',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const RecomendacoesRoute = RecomendacoesRouteImport.update({
  id: '/recomendacoes',
  path: '/recomendacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialNetworkRoute = SocialNetworkRouteImport.update({
  id: '/social/$network',
  path: '/social/$network',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/boas-vindas': typeof BoasVindasRoute
  '/ranking': typeof RankingRoute
  '/recomendacoes': typeof RecomendacoesRoute
  '/social/$network': typeof SocialNetworkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/boas-vindas': typeof BoasVindasRoute
  '/ranking': typeof RankingRoute
  '/recomendacoes': typeof RecomendacoesRoute
  '/social/$network': typeof SocialNetworkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/boas-vindas': typeof BoasVindasRoute
  '/ranking': typeof RankingRoute
  '/recomendacoes': typeof RecomendacoesRoute
  '/social/$network': typeof SocialNetworkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/boas-vindas'
    | '/ranking'
    | '/recomendacoes'
    | '/social/$network'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/boas-vindas'
    | '/ranking'
    | '/recomendacoes'
    | '/social/$network'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/boas-vindas'
    | '/ranking'
    | '/recomendacoes'
    | '/social/$network'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  BoasVindasRoute: typeof BoasVindasRoute
  RankingRoute: typeof RankingRoute
  RecomendacoesRoute: typeof RecomendacoesRoute
  SocialNetworkRoute: typeof SocialNetworkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boas-vindas': {
      id: '/boas-vindas'
      path: '/boas-vindas'
      fullPath: '/boas-vindas'
      preLoaderRoute: typeof BoasVindasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recomendacoes': {
      id: '/recomendacoes'
      path: '/recomendacoes'
      fullPath: '/recomendacoes'
      preLoaderRoute: typeof RecomendacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/$network': {
      id: '/social/$network'
      path: '/social/$network'
      fullPath: '/social/$network'
      preLoaderRoute: typeof SocialNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  BoasVindasRoute: BoasVindasRoute,
  RankingRoute: RankingRoute,
  RecomendacoesRoute: RecomendacoesRoute,
  SocialNetworkRoute: SocialNetworkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
